### ISSUE TITLE
Pundit::AuthorizationNotPerformedError: ActivitiesController

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#100]
https://sentry.io/share/issue/013945a97f5d4f7aa90cee9242cf5a79/

```
Pundit::AuthorizationNotPerformedError: ActivitiesController
  pundit.rb:178:in `verify_authorized'
    raise AuthorizationNotPerformedError, self.class unless pundit_policy_authorized?
  active_support/callbacks.rb:426:in `block in make_lambda'
    target.send(method, *arguments, &block)
  active_support/callbacks.rb:236:in `block in halting_and_conditional'
    user_callback.call target, value
  active_support/callbacks.rb:517:in `block in invoke_after'
    @after.each { |a| a.call(arg) }
  active_support/callbacks.rb:517:in `each'
    @after.each { |a| a.call(arg) }
...
(63 additional frame(s) were not displayed)

Pundit::AuthorizationNotPerformedError: ActivitiesController
```

**Comment by nathanpalmer** [comment]
This one I might need access to Sentry to view. I'm missing some information such as what URL was getting used.

**Comment by Shpigford** [comment]
@nathanpalmer Does this give you enough info? https://sentry.io/share/issue/013945a97f5d4f7aa90cee9242cf5a79/

And it occurred on `https://alpha.rockburg.com/bands/255/activities/new`

**Comment by nathanpalmer** [comment]
The URL helps. Yeah, I think I've got the right one. You'll just have to let me know if any others popup.
