### ISSUE TITLE
Could not connect to server

### ISSUE THREAD

**Issue by Shpigford** [Rockburg/rockburg#18]
Getting this error when trying to spin up the worker on Heroku.

```
2018-04-12T18:03:43.469255+00:00 app[worker.1]: 4 TID-2vsu0 INFO: Booting Sidekiq 5.1.3 with redis options {:url=>"redis://redistogo:REDACTED@tarpon.redistogo.com:11380/", :id=>"Sidekiq-server-PID-4"}
2018-04-12T18:03:44.823890+00:00 app[worker.1]: I, [2018-04-12T18:03:44.823709 #4]  INFO -- : DB Connection Pool size for Sidekiq Server before disconnect is: 5
2018-04-12T18:03:44.827892+00:00 app[worker.1]: could not connect to server: No such file or directory
2018-04-12T18:03:44.827897+00:00 app[worker.1]: 	Is the server running locally and accepting
2018-04-12T18:03:44.827900+00:00 app[worker.1]: 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2018-04-12T18:03:44.829143+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/pg-1.0.0/lib/pg.rb:56:in `initialize'
2018-04-12T18:03:44.829146+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/pg-1.0.0/lib/pg.rb:56:in `new'
2018-04-12T18:03:44.829147+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/pg-1.0.0/lib/pg.rb:56:in `connect'
2018-04-12T18:03:44.829151+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
2018-04-12T18:03:44.829153+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
2018-04-12T18:03:44.829155+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
2018-04-12T18:03:44.829157+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
2018-04-12T18:03:44.829158+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
2018-04-12T18:03:44.829161+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
2018-04-12T18:03:44.829163+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
2018-04-12T18:03:44.829164+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
2018-04-12T18:03:44.829166+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
2018-04-12T18:03:44.829168+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
2018-04-12T18:03:44.829169+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
2018-04-12T18:03:44.829171+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
2018-04-12T18:03:44.829173+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:90:in `connection'
2018-04-12T18:03:44.829175+00:00 app[worker.1]: /app/config/initializers/sidekiq.rb:22:in `block (3 levels) in <top (required)>'
2018-04-12T18:03:44.829176+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
2018-04-12T18:03:44.829178+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
2018-04-12T18:03:44.829180+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
2018-04-12T18:03:44.829182+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
2018-04-12T18:03:44.829183+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
2018-04-12T18:03:44.829186+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:42:in `each'
2018-04-12T18:03:44.829188+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
2018-04-12T18:03:44.829189+00:00 app[worker.1]: /app/config/initializers/sidekiq.rb:15:in `block (2 levels) in <top (required)>'
```

**Comment by peterkeen** [comment]
That's a postgres error. Is DATABASE_URL set?

**Comment by Shpigford** [comment]
@peterkeen It is indeed set.

**Comment by Shpigford** [comment]
@peterkeen Do database.yml settings have any affect on this?

https://github.com/Rockburg/rockburg/blob/master/config/database.yml

**Comment by Shpigford** [comment]
This commit solved the issue...though I have no idea why: https://github.com/Rockburg/rockburg/commit/568558d8b27b6f215efcb8fd5720b6dd0f3c25d4

(Saw someone on Stackoverflow mention it, though they didn't know why either)

**Comment by peterkeen** [comment]
Huh. Well, I'm glad it's working!
